---
- hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
    - name: Check connection
      ping:
    
    - name: Update
      ansible.builtin.apt:
        update_cache: yes

    - name: Pull image
      community.docker.docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ VAULT_REDMINE_DB_POSTGRES }}"
          REDMINE_DB_USERNAME: "{{ VAULT_REDMINE_DB_USERNAME }}"
          REDMINE_DB_PASSWORD: "{{ VAULT_REDMINE_DB_PASSWORD }}"
          REDMINE_DB_DATABASE: "{{ VAULT_REDMINE_DB_DATABASE }}"
          REDMINE_DB_PORT: "{{ VAULT_REDMINE_DB_PORT }}"