---
- hosts: localhost
  tasks:
    - name: Prepare infrasctucture
      community.general.terraform:
        project_path: '../terraform/'
        state: present
        variables:
          do_token: "{{ VAULT_DO_TOKEN }}"
        workspace: homework
      register: infrastructure

    - name: Render hosts.ini
      template:
        src: hosts.j2
        dest: hosts.ini

- hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
    - name: Check connection
      ping:

    - name: Update
      ansible.builtin.apt:
        update_cache: yes

    - name: Pull image
      community.docker.docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ hostvars.localhost.infrastructure.outputs.database.value.host }}"
          REDMINE_DB_USERNAME: "{{ hostvars.localhost.infrastructure.outputs.database.value.user }}"
          REDMINE_DB_PASSWORD: "{{ hostvars.localhost.infrastructure.outputs.database.value.password }}"
          REDMINE_DB_DATABASE: "{{ hostvars.localhost.infrastructure.outputs.database.value.database }}"
          REDMINE_DB_PORT: "{{ hostvars.localhost.infrastructure.outputs.database.value.port }}"