---
- hosts: webservers
  roles:
    - { role: geerlingguy.docker }
    - { role: geerlingguy.pip }
    - { role: datadog.datadog, become: yes }
  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: yes

    - name: Pull image
      community.docker.docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"