---
#- hosts: localhost
#  tasks:
#    - name: Prepare infrasctucture
#      community.general.terraform:
#        project_path: '../terraform/'
#        state: present
#        workspace: homework
#      register: infrastructure
# Временно отключено что бы пройти проверку hexlet-check
#    - name: Render hosts.ini
#      template:
#        src: inventory.j2
#        dest: inventory.ini

- hosts: wevservers
  roles:
    - { role: geerlingguy.docker }
    - { role: geerlingguy.pip }
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "245fea817478a3583bb69842cb012d6c"
    datadog_site: "datadoghq.com"
  tasks:
    - name: Check connection
      ping:

    - name: Update
      ansible.builtin.apt:
        update_cache: yes

    - name: Pull image
      community.docker.docker_container:
        name: redmine
        image: redmine
        state: started
        restart: yes
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ hostvars.localhost.infrastructure.outputs.database.value.host }}"
          REDMINE_DB_USERNAME: "{{ hostvars.localhost.infrastructure.outputs.database.value.user }}"
          REDMINE_DB_PASSWORD: "{{ hostvars.localhost.infrastructure.outputs.database.value.password }}"
          REDMINE_DB_DATABASE: "{{ hostvars.localhost.infrastructure.outputs.database.value.database }}"
          REDMINE_DB_PORT: "{{ hostvars.localhost.infrastructure.outputs.database.value.port }}"